### ISSUE TITLE
Backbone js and current API compatibility

### ISSUE THREAD

**Issue by are2** [SkeneApp/Backend#1]
The current server API is not working out-of-box with Backbone. The main reason is that Backbone's "model.save()" function is sending json formatted HTTP post data and I think that current API is expecting traditional HTML post data? One solution is that we write extension for Backbone Model.save, but I think a better solution is to make json support for server side API.

Getting data from the server to Backbone model is quite simple and it is working right now. I just tested it and I was able to get latest messages with the server API get_latest function:

<pre lang="javascript"><code>
        Message = Backbone.Model.extend(
        {
            defaults: 
            {
                "id": 0,
                "latitude": 0,
                "longitude": 0,
                "pubTime": 0,
                "text": ""
            },

            initialize: function(){
            }
        });

        LatestMessages = Backbone.Collection.extend(
        {
            url: "http://whispr.outi.me/api/get_latest?json=true",
            model: Message
        });

        var latestMessages = new LatestMessages;

        function GetLatestMessages()
        {
            latestMessages.fetch(
            {
                success: function()
                {
                    ShowLatestMessages(10);
                },
                error: function(){

                }
            });
        }

        function ShowLatestMessages(limit)
        {
            var msg = "";
            latestMessages.forEach(function(item)
            {
                if (limit > 0)
                {
                    msg += item.get("text") + "\r\n";
                    limit--;
                }
            });

            alert(msg);
        }
</code></pre>

**Comment by sarukuku** [comment]
I think we should go with backend modification. Could you do that @are2 ? :)

**Comment by sarukuku** [comment]
Good work by the way!

**Comment by timojaask** [comment]
As I was working on improving the WP8 beta app, I ran into the same issue with saving data. So I added a new function to the server API that fits better. It's called add_json. The only difference to the old add command is that it uses the same JSON data format as the get functions, so it allows you to use the same model for getting and saving. I have no idea why we made them different in the first place! :D

Antti, I will give you credentials to access the server software, so you can modify it if needed.

I'm clueless about PHP, so fix it if it's messed up! I have just committed this to GitHub Backend repo.

``` php
public function add_json()
{
    $json = json_decode(trim(file_get_contents('php://input')));
    $data = array(
        'latitude'  =>  $json->latitude,
        'longitude' =>  $json->longitude,
        'text'      =>  $json->text,
        'pubTime'   =>  time() + $json->pubTime
    );

    $this->db->insert('whispers', $data);

    // TODO: would be nice if this function returned
    // the ID of the new message.
    echo "123";
}
```

**Comment by timojaask** [comment]
So just for the record, it works now. You can get and post in REST style :+1:

**Comment by sarukuku** [comment]
:+1:
