### ISSUE TITLE
Talk about API

### ISSUE THREAD

**Issue by timojaask** [SkeneApp/Backend#10]
Need to agree on one reasonable way of doing this API, implement it and use it. Shouldn't take long.

**Comment by daitj** [comment]
I think I have mentioned this earlier why not have something like this:
https://github.com/themightydeity/simple-api

it is simple and as we just need our api to return json data we don't need to load all the CI classes. Anyway we have been doing db query directly in controller it fits perfectly for us. We don't have user auth we just need plain api to return json as fast as possible.

Well this doesn't answer your question @timojaask but IMO we should finalize on things we need (if we haven't done that already) from api and start fixing it all together.

**Comment by timojaask** [comment]
API v2 initial implementation done. Thanks everyone!
