### ISSUE TITLE
need support for center and raidus instead of maximum and minumum longitude/latitude

### ISSUE THREAD

**Issue by daitj** [SkeneApp/Backend#2]
The current API only accepts maximum and minimum longitude/latitude for fetching the messages in certain area. But in reality we have to use center location with radius of the selection circle. I am just thinking it is easier to implement Radius to Min/Max in backend.

As mentioned here in this website:
http://www.movable-type.co.uk/scripts/latlong-db.html 

It can be done by using the cosine law:
    d = acos( sin(φ1).sin(φ2) + cos(φ1).cos(φ2).cos(Δλ) ).R
where:  φ = latitude, λ = longitude
    R = radius of earth
    d = distance between the points
Written out as it would be coded, this is
    d = acos(sin(lat1)_sin(lat2) + cos(lat1)_cos(lat2)_cos(lon2-lon1))_R

For PHP:
// Inputs $rad = Radius, $lat = Latitude, $lon = Longitude

$R = 6371;  // earth's mean radius, km
// first-cut bounding box (in degrees)
$maxLat = $lat + rad2deg($rad/$R);
$minLat = $lat - rad2deg($rad/$R);

// compensate for degrees longitude getting smaller with increasing latitude
$maxLon = $lon + rad2deg($rad/$R/cos(deg2rad($lat)));
$minLon = $lon - rad2deg($rad/$R/cos(deg2rad($lat)));

$sql = "Select Aything,Lat, Lon
        From TABLE
        Where Lat Between :minLat And :maxLat
          And Lon Between :minLon And :maxLon";

**Comment by timojaask** [comment]
Do you have access to the server? If not, let me know and I'll give you the credentials, so you can implement it.

**Comment by daitj** [comment]
The old credentials are not working anymore. I think you have send me new one.

**Comment by timojaask** [comment]
Sent.

**Comment by daitj** [comment]
#2 Fixed
