### ISSUE TITLE
Securing the communication

### ISSUE THREAD

**Issue by sarukuku** [SkeneApp/Backend#5]
Based on the short converation we had at some dev meeting. I've been googling a bit and at some point I found [this](http://stackoverflow.com/questions/9823391/how-to-make-sure-api-requests-come-from-our-mobile-ios-android-app#answer-9824996). I think this is quite close to what we should be doing.

**Comment by are2** [comment]
I have read about the HMAC authentication (for example Amazon uses it to secure REST api). HMAC is quite simple to implement and the good thing is that no private API keys (user generated or global) are passed over the internet.

Basically you just combine all the data you want to pass to the server and calculate a HMAC hash of it with a private key. Then you transmit the data, public key (=user id) and the hash to the server. The server now calculates hash again and if it match then it handles the request.

http://en.wikipedia.org/wiki/HMAC

What you think?

**Comment by zaynetro** [comment]
This is a good article:
http://www.thebuzzmedia.com/designing-a-secure-rest-api-without-oauth-authentication/

It describes how auth works based on Amazon experience
